#!/usr/bin/env tclsh
# Copyright 2008-2010,2014-2016 BitMover, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Create all the files for fslayer stubs:
#   fslayer.h
#   fslayer_XXX_stub.c
#   fslayer.makefile

set here [file dirname [info script]]
cd $here

set bigcmt [join {
"// *******************************************************"
"// XXX This file is automatically generated."
"//     Edit gen_fslayer.pl instead"
"//"
"// DO NOT EDIT THIS FILE, YOUR CHANGES WILL BE LOST !!!!!!"
"// *******************************************************"
} "\n"]
append bigcmt "\n\n"

set prototypes {
"int     fslayer_open(const char *path, int flags, mode_t mode);"
"int     fslayer_close(int fd);"
"ssize_t fslayer_read(int fd, void *buf, size_t count);"
"ssize_t fslayer_write(int fd, const void *buf, size_t count);"
"off_t   fslayer_lseek(int fildes, off_t offset, int whence);"
"int     fslayer_lstat(const char *path, struct stat *buf);"
"int     fslayer_linkcount(const char *path, struct stat *buf);"
"int     fslayer_fstat(int fd, struct stat *buf);"
"int     fslayer_stat(const char *path, struct stat *buf);"
"int     fslayer_unlink(const char *path);"
"int     fslayer_rename(const char *old, const char *new);"
"int     fslayer_chmod(const char *path, mode_t mode);"
"int     fslayer_link(const char *old, const char *new);"
"int     fslayer_symlink(const char *old, const char *new);"
"char**  fslayer_getdir(char *dir);"
"int     fslayer_access(const char *path, int mode);"
"int     fslayer_utime(const char *path, const struct utimbuf *buf);"
"int     fslayer_mkdir(const char *path, mode_t mode);"
"int     fslayer_rmdir(const char *path);"
"int     fslayer_rmIfRepo(char *path);"
"char*   fslayer_realBasename(const char *path, char *realname);"
}

set fcns {}
array unset data
foreach line $prototypes {
    if {![regexp {^(.*)\s+fslayer_(.*)\((.*)\);$} $line -> ret fcn args]} {
        continue
    }
    set argList {}
    foreach a [split $args ,] {
        set a [string trim $a]
        lappend argList $a
    }
    lappend fcns $fcn
    set data($fcn,RET) $ret
    set data($fcn,ARGS) [join $argList ", "]
    set names {}
    foreach a $argList {
        if {[regexp {(\w+)$} $a -> name]} {
            lappend names $name
        }
    }
    set data($fcn,ANAMES) [join $names ", "]
}

# Generate fslayer.h
set h [open "fslayer.h" w]
puts $h "// fslayer.h"
puts $h $bigcmt
puts $h "#ifndef\tFSLAYER_NODEFINES"
foreach f $fcns {
    puts $h "#undef\t$f"
    puts $h [format "#define\t%s(%s) fslayer_%s(%s)" $f $data($f,ANAMES) $f $data($f,ANAMES)]
}
puts $h "#endif\n"
foreach f $fcns {
    puts $h [format "%s\tfslayer_%s(%s);" $data($f,RET) $f $data($f,ARGS)]
}
close $h
file attributes fslayer.h -permissions 0444

# Generate stub sources
foreach f $fcns {
    set fname [format "fslayer_%s_stub.c" $f]
    set s [open $fname w]
    puts $s "// $fname"
    puts $s $bigcmt
    puts $s "#define\tFSLAYER_NODEFINES"
    puts $s "#include \"system.h\""
    puts $s "#include \"win_remap.h\""
    puts $s ""
    puts $s $data($f,RET)
    puts $s [format "fslayer_%s(%s)" $f $data($f,ARGS)]
    puts $s "{"
    puts $s [format "\treturn (%s(%s));" $f $data($f,ANAMES)]
    puts $s "}"
    close $s
    file attributes $fname -permissions 0444
}

# Generate makefile fragment
set m [open "fslayer.makefile" w]
puts $m "# fslayer.makefile"
set bigcmtmk [string map {"/" "#"} $bigcmt]
puts -nonewline $m $bigcmtmk
puts $m [format "FSLAYER_OBJS = %s" [join [lmap f $fcns {format "fslayer/fslayer_%s_stub.o" $f}] " "]]
puts $m ""
puts $m "FSLAYER_HDRS = fslayer/fslayer.h"
puts $m ""
puts $m "JUNK += fslayer/fslayer.h fslayer/fslayer.makefile \\\n\t[join [lmap f $fcns {format "fslayer/fslayer_%s_stub.c" $f}] " "]"
puts $m ""
puts $m "fslayer: \$(FSLAYER_OBJS)"
close $m
file attributes fslayer.makefile -permissions 0444
