#!/usr/bin/env tclsh
# Copyright 2012-2013,2015-2016 BitMover, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set tmp "cfgtest[pid].c"
set defset {}
set lines {}

set out [open $tmp w]
puts $out "#define MK_STR_CFG"

set fh [open "local_string.h" r]
set lineno 0
while {[gets $fh line] >= 0} {
    incr lineno
    if {[regexp {ifdef\s+(\w+)} $line -> macro]} {
        puts $out "#define $macro"
        dict set defset $macro 1
        dict set lines [expr {$lineno + 1}] $macro
    }
}
close $fh
puts $out "#include \"local_string.h\""
close $out

set cc [expr {[info exists ::env(CC)] ? $::env(CC) : "gcc"}]
set cmd "$cc -I.. -Wredundant-decls $tmp"
set gcc [open "|$cmd 2>@1" r]
while {[gets $gcc line] >= 0} {
    if {[regexp {local_string\.h:(\d+)} $line -> lnum]} {
        if {[dict exists $lines $lnum]} {
            set macro [dict get $lines $lnum]
            if {[dict exists $defset $macro]} {
                dict unset defset $macro
            }
        }
    }
}
close $gcc

set out [open $tmp w]
puts $out "// autogenerated file"
puts $out "// this enables all string functions not in the C library"
foreach macro [lsort [dict keys $defset]] {
    puts $out "#define $macro"
    puts "#define $macro"
}
close $out

file rename -force $tmp "str.cfg"
